language: python
python: 3.5
sudo: required

virtualenv:
  –system-site-packages

notifications:
  email: false

before_install:
 - sudo apt-get install -qq python-numpy python-scipy

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install testfixtures

script:
  - python setup.py develop
  - py.test --cov=creamas tests/
  - py.test --doctest-glob="*.rst" docs/
  - flake8 creamas tests

after_success:
  - coveralls
