language: python
python:
  - "3.6"
  - "3.7"
sudo: false

notifications:
  email: false

install:
  - pip install tox
  - pip install coveralls
  - pip install aiomas
  - pip install tox-travis
  - pip install scipy
  - pip install noise
  - pip install deap
  - pip install networkx
  - pip install opencv-python

script:
  - tox -e $TOXENV

env:
  - TOXENV=py37
  - TOXENV=docs
  - TOXENV=flake8

after_success:
  - coveralls
