language: python
python: 3.5

notifications:
  email: false

addons:
  apt:
    packages:
    - python-numpy
    - python-scipy

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install testfixtures

script:
  - python setup.py develop
  - py.test --cov=creamas tests/
  - py.test --doctest-glob="*.rst" docs/
  - flake8 creamas tests

after_success:
  - coveralls
