language: python
python:
  - "3.5"
sudo: false

notifications:
  email: false

install:
  - pip install tox
  - pip install coveralls
  - pip install aiomas
  - pip install tox-travis

script:
  - tox -e $TOXENV

env:
  - TOXENV=py35
  - TOXENV=docs
  - TOXENV=flake8

after_success:
  - coveralls
