language: python
python: 3.5
sudo: false

notifications:
  email: false

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
    - python-numpy
    - python-scipy

install:
  - pip install tox
  - pip install coveralls

script:
  - tox

env:
  - TOXENV=py35
  - TOXENV=docs
  - TOXENV=flake8

after_success:
  - coveralls
