language: python
python: 3.5
sudo: false

notifications:
  email: false

#addons:
#  apt:
#    packages:
#    - python-numpy
#    - python-scipy

install:
  - pip install --user -r requirements.txt
  - pip install tox
  - pip install coveralls

script:
  - tox

env:
  - TOXENV=py35
  - TOXENV=docs
  - TOXENV=flake8

after_success:
  - coveralls
