language: python
python: 3.5
sudo: false

notifications:
  email: false

install:
  - pip install tox
  - pip install coveralls

script:
  - tox

env:
  - TOXENV=py35
  - TOXENV=docs
  - TOXEND=flake8

after_success:
  - coveralls
